accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.signin, name="login"),
    path("logout/", views.signout, name="logout"),
    path("verify/", views.inform_to_verify, name="verify"),
    path("follow/", views.Follow.as_view(), name="follow"),
    path("like/", views.LikePost.as_view(), name="like"),
    path("bookmark/", views.BookmarkPost.as_view(), name="bookmark"),
    path("confirm/<uidb64>/<token>/", views.activate, name="activate"),
    path("<str:uid>/", views.UserProfile.as_view(), name="profile"),
    path("<str:uid>/update/", views.update_profile, name="update-profile"),
    path("<str:uid>/draft/", views.DraftPostList.as_view(), name="draft"),
    path("<str:uid>/saved/", views.SavedPostList.as_view(), name="saved"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("stories/", views.PostList.as_view(), name="post-list"),
    path("search", views.SearchResultsList.as_view(), name="search"),
    path("p/new/", views.PostCreate.as_view(), name="post-create"),
    path("p/<slug:slug>/", views.PostDetail.as_view(), name="post-detail"),
    path("p/<slug:slug>/edit/", views.PostUpdate.as_view(), name="post-update"),
    path("p/<slug:slug>/delete/", views.PostDelete.as_view(), name="post-delete"),
    path("p/<slug:slug>/comments/", views.comments, name="comment-list"),
    path(
        "p/<slug:slug>/comments/<int:pk>/edit/",
        views.CommentUpdate.as_view(),
        name="comment-update",
    ),
    path(
        "p/<slug:slug>/comments/<int:pk>/delete/",
        views.CommentDelete.as_view(),
        name="comment-delete",
    ),
    path("category/<slug:slug>/", views.CategoryView.as_view(), name="category"),
]

django_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("blog.urls")),
    path("ac/", include("accounts.urls")),
    path(
        "accounts/reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Account, Profile


class LoginForm(forms.ModelForm):
    """Form used to log a user in."""

    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password"}),
    )

    class Meta:
        model = Account
        fields = ["email", "password"]


class SignupForm(UserCreationForm):
    """Form used to register the user."""

    class Meta:
        model = Account
        fields = ["first_name", "last_name", "email", "password1", "password2"]


class UserUpdateForm(forms.ModelForm):
    """Form used to update user information."""

    class Meta:
        model = Account
        fields = ["first_name", "last_name"]


class ProfileUpdateForm(forms.ModelForm):
    """Form used to update profile of the user."""

    class Meta:
        model = Profile
        fields = ["title", "about"]

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import ListView, View

from blog.models import Post

from .forms import LoginForm, ProfileUpdateForm, SignupForm, UserUpdateForm
from .models import Account, Bookmark, Like, UserFollowing
from .tokens import email_confirmation_token


class UserProfile(ListView):
    """Show profile of the user and all posts posted by the user."""

    context_object_name = "author_posts"
    template_name = "accounts/user_profile.html"
    paginate_by = 10

    def get_queryset(self):
        # Filtering posts by the user only
        self.user = get_object_or_404(Account, uid=self.kwargs.get("uid"))
        return (
            Post.objects.filter(author=self.user)
            .select_related("category")
            .select_related("author")
            .filter(status=1)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.user
        return context


class DraftPostList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """Show list of draft post that has not been published."""

    template_name = "accounts/user_draft.html"
    context_object_name = "draft_posts"

    def get_queryset(self):
        return (
            Post.objects.filter(author=self.request.user)
            .select_related("category")
            .filter(status=0)
            .order_by("-last_update")
        )

    def test_func(self):
        # check the user trying to view drafts is the owner
        self.user = get_object_or_404(Account, uid=self.kwargs.get("uid"))
        return self.request.user == self.user


class SavedPostList(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """Show list of bookmarked posts."""

    template_name = "accounts/user_saved.html"
    context_object_name = "bookmarks"

    def get_queryset(self):
        return (
            Bookmark.objects.select_related("post")
            .filter(user=self.request.user)
            .order_by("-saved_at")
        )

    def test_func(self):
        # check the user trying to view drafts is the owner
        self.user = get_object_or_404(Account, uid=self.kwargs.get("uid"))
        return self.request.user == self.user


class BookmarkPost(View):
    """Handle bookmarking post using ajax calls."""

    def post(self, request):
        user = self.request.user
        if user.is_authenticated:
            # bookmark selected post
            post_id = request.POST.get("post_id")
            selected_post = Post.objects.get(pk=post_id)
            is_bookmarked = False  # initial assumption
            bookmark = Bookmark.objects.filter(user=user, post=selected_post).first()
            if bookmark:
                # The user has already saved it, unsave now
                bookmark.delete()
            else:
                # save the bookmark now
                Bookmark.objects.create(user=user, post=selected_post)
                is_bookmarked = True
            return JsonResponse(
                {"is_bookmarked": is_bookmarked, "post_id": post_id}, status=200
            )
        else:
            # Not authenticated
            messages.warning(
                self.request,
                "Login to your account to bookmark posts.",
            )
            return JsonResponse({"is_bookmarked": False}, status=401)


class Follow(View):
    """Handle Follow and Unfollow process."""

    def post(self, request):
        current_user_id = self.request.user.pk
        if self.request.user.is_authenticated:
            # the user making the request
            current_user = Account.objects.get(pk=current_user_id)

            # ID of the user to follow or unfollow
            user_id = request.POST["user_id"]
            target_user = Account.objects.get(pk=user_id)
            is_following = False  # initial assumption

            # All users followed by current user (following wrt to the user)
            following = [f.user_following for f in current_user.following.all()]

            if not target_user in following:
                # Start following now
                print(f"I am here 2 {current_user} following {target_user} now.")
                UserFollowing.objects.create(
                    user=current_user, user_following=target_user
                )
                is_following = True
            else:
                # It was already following, Unfollow the user now
                print(f"I am here 3 {current_user} stops following {target_user} now.")
                UserFollowing.objects.filter(
                    user=current_user, user_following=target_user
                ).delete()
            return JsonResponse({"is_following": is_following}, status=200)
        else:
            messages.info(
                self.request,
                "Login to your account to follow other users.",
            )
            return JsonResponse({"not_authenticated": True}, status=401)


class LikePost(View):
    """Handle like and unlike posts."""

    def post(self, request):

        user = self.request.user
        if user.is_authenticated:
            # the user is authenticated, go to like activity
            user = Account.objects.get(pk=user.pk)
            post_id = request.POST.get("post_id")
            selected_post = Post.objects.get(pk=post_id)
            is_liked = False  # initial assumption
            if not selected_post in user.profile.likes:
                # Like the post now
                Like.objects.create(user=user, post=selected_post)
                is_liked = True
            else:
                # Unlike the post
                Like.objects.filter(user=user, post=selected_post).delete()

            data = {"is_liked": is_liked, "likes_count": selected_post.like_set.count()}
            return JsonResponse(data, status=200)
        else:
            messages.info(
                self.request,
                "Login to your account to like posts.",
            )
            return JsonResponse(data={"is_liked": False}, status=401)


def signin(request):
    """Display login form and handle the login process."""
    if request.user.is_authenticated:
        return redirect("blog:post-list")

    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect("blog:post-list")
        else:
            messages.error(request, "Invalid Email or Password.")
    login_form = LoginForm()
    context = {"login_form": login_form}
    return render(request, "accounts/login.html", context)


def signout(request):
    """Log the user out."""
    logout(request)
    return redirect("blog:post-list")


def signup(request):
    """Display signup form and handle the signup action."""

    if request.method == "POST":
        # the user has submitted the form (POST request): get the data submitted
        signup_form = SignupForm(request.POST)
        if signup_form.is_valid():
            try:
                user = signup_form.save(commit=False)
                user.is_active = False  # until the user confirms the email
                user.save()

                # send verification email
                current_site = get_current_site(request)
                mail_subject = "Verify your email address"
                message = render_to_string(
                    "accounts/confirm_email.html",
                    {
                        "user": user,
                        "domain": current_site.domain,
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "token": email_confirmation_token.make_token(user),
                    },
                )
                to_email = signup_form.cleaned_data.get("email")
                email = EmailMessage(mail_subject, message, to=[to_email])
                email.send()
            except Exception as error:
                print("Error: Error occurred while registering the user. Retrying...")
                print(error.with_traceback())

            # Set user email to session variable to pass it to another view
            first_name = signup_form.cleaned_data.get("first_name")
            request.session["first_name"] = first_name
            return redirect(to=reverse("accounts:verify"))
    else:
        # it is GET request: display an empty signup form
        signup_form = SignupForm()

    context = {"signup_form": signup_form}
    return render(request, "accounts/signup.html", context)


def activate(request, uidb64, token):
    """Activate the user account after the confirms their email address."""
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and email_confirmation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # Automatically log the user in up on successful confirmation
        login(request, user)
        messages.success(request, "Your email has been verified successfully.")
        messages.success(

accounts/templates/accounts/confirm_email.html
{% autoescape off %}
Hi {{ user.first_name }}!

Please click on the link below to confirm your email address.

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Login to Tomar {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid bg-light pb-5">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-4 mx-auto">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show pb-2" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            <div class="card border-0 shadow rounded-3 my-4">
                <div class="card-body p-3 p-sm-4">
                    <h5 class="card-title text-center fw-light fs-5">Tomar Login</h5>
                    <form method="POST"> {% csrf_token %}
                        <div class="mb-3">
                            <input type="email" class="form-control" name="email" placeholder="Email" required>
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" name="password" placeholder="Password" required>
                        </div>
                        <div class="d-flex justify-content-between mb-3">
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" id="remember">
                                <label class="form-check-label small" for="remember">Remember me</label>
                            </div>
                            <div class="text-end small">
                                <a href="{% url 'password_reset' %}">Forgot password?</a>
                            </div>
                        </div>
                        <div class="d-grid">
                            <button class="btn btn-primary btn-block" type="submit"> Sign in </button>
                        </div>
                        <br>
                        <div class="text-center">
                            Don't have an account?
                            <a href="{% url 'accounts:signup'%}">Create one</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Password reset complete {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid main">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-4 mx-auto">
      <div class="card border-0 shadow rounded-3 my-5">
        <div class="card-body p-4 p-sm-5" style="box-shadow: 0 0 10px rgba(71, 71, 71, 0.4);">
          <h5 class="card-title mb-4 fw-light fs-5">Password reset complete</h5>
          <hr class="my-4" />
          <p>
            Your password has been reset successfully! You can now
            <a href="{% url 'accounts:login' %}"> Sign in to your account</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Password Reset Confirm {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid main">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <div class="card border-0 shadow rounded-3 my-5">
        <div class="card-body p-4 p-sm-5" style="box-shadow: 0 0 10px rgba(71, 71, 71, 0.4);">
          <h5 class="card-title text-center mb-5 fw-light fs-5">New Password</h5>
          <form method="POST"> {% csrf_token %}
            {{ form|crispy }}

            <div class="d-grid">
              <button class="btn btn-primary btn-block" type="submit"> Reset password </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Sign Up for Tomar {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid bg-light pb-5">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 mx-auto">
      <div class="card border-0 shadow rounded-3 my-4">
        <div class="card-body p-4">
          <h5 class="card-title text-center fw-light mb-3 fs-5">Create a new Account</h5>
          <form method="POST"> {% csrf_token %}
            {{ signup_form|crispy }}
            <div class="d-grid">
              <button class="btn btn-primary btn-block" type="submit"> Sign up </button>
            </div>
            <br />
            <div class="text-center">
              Already have an account?
              <a href="{% url 'accounts:login'%}">Sign in</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Update profile {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid main">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-lg-7 mx-auto">
                <div class="card border-0 shadow rounded-3 my-5">
                    <div class="card-body p-4 p-sm-5" style="box-shadow: 0 0 5px rgba(71, 71, 71, 0.4);">
                        <h5 class="card-title text-center mb-4 fw-light fs-5">Share you ideas to the world</h5>
                        <form method="POST" style="overflow: auto;"> {% csrf_token %}
                            {{ user_form|crispy }}
                            {{ profile_form|crispy }}
                            <div>
                                <button class="btn btn-primary mr-2" type="submit" id="submitBtn">Update</button>
                                <a class="btn btn-secondary" href="{% url 'accounts:profile' user.uid %}">Cancel </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}
{% endblock %}

accounts/templates/accounts/user_draft.html
{% extends "base.html" %}
{% load post_read_time %}

{% block title %} Draft posts {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid">
    <div class="px-md-5 pt-4">
        <div class="row">
            <div class="col-12 col-md-8 col-lg-6 mx-auto">
                <!-- Author posts -->
                {% if draft_posts|length > 0 %}
                {% for post in draft_posts %}
                <div class="col-12 mx-auto">
                    <div class="mycard">
                        <div class="d-flex flex-column">
                            <h4 class="card-title">
                                <a href="{% url 'blog:post-detail' post.slug %}" class="mb-2 lh-sm">{{ post.title }}</a>
                            </h4>
                        </div>
                        <div
                            class="mb-0 text-muted d-flex align-items-end align-items-md-center justify-content-between">
                            <div>
                                <a class="d-none d-md-inline category-btn"
                                    href="{% url 'blog:category' post.category.slug %}">{{ post.category }}</a>
                                <span>{{ post.last_update|date:"M d" }}</span><span
                                    class="dot"></span><span>{{ post.content|readtime }}</span>
                            </div>
                            <div class="action">
                                <a href="{% url 'blog:post-update' post.slug %}" title="Edit post"><i
                                        class="far fa-edit"></i></a>
                                <a href="{% url 'blog:post-delete' post.slug %}" class="ms-1" title="Delete post"><i
                                        class="fas fa-trash"></i></a>
                            </div>
                        </div>
                    </div>
                    <!-- End author post -->
                    <hr class="my-3" />
                </div>
                {% endfor %}
                {% else %}
                <div class="col-12 col-lg-6 mx-auto">
                    <p>You don't have any draft posts yet. Start writing to edit it any time.</p>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/user_profile.html
{% extends "base.html" %}
{% load static %}
{% load post_read_time %}

{% block title %} Profile {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid a-hero">
    <div class="row">
        <div class="container pt-2 pb-3">
            <div class="col-md-7 mx-auto">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show pb-2" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="d-flex flex-column align-items-center">
                <div class="flex-grow-1 pt-2">
                    <div class="d-flex align-items-center justify-content-center justify-content-md-start mb-0">
                        <span class="me-2 fs-4">{{ user.get_full_name }}</span>
                        {% if request.user == user %}
                        <a href="{% url 'accounts:update-profile' user.uid %}" title="Update your profile"><i
                                class="fas fa-user-edit ms-2"></i></a>
                        {% elif request.user in user.profile.followers %}
                        <button class="btn btn-sm btn-outline-primary follow" value="{{ user.pk }}">Following</button>
                        {% else %}
                        <button class="btn btn-sm btn-primary follow" value="{{ user.pk }}">Follow</button>
                        {% endif %}
                    </div>
                    <p class="text-md-start text-center">
                        {{ user.profile.title }}
                    </p>
                    <div class="text-muted text-md-start text-center mt-2">
                        <span>{{ user.profile.followers|length }} Followers</span><span
                            class="dot"></span><span>{{ user.profile.following|length }}
                            Following</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row pt-4">
        <div class="col-md-8">
            <!-- Author posts -->
            {% if author_posts|length > 0 %}
            {% for post in author_posts %}
            <div class="col-12 col-lg-9 mx-auto">
                <div class="mycard">
                    <div class="d-flex flex-column">
                        <h4 class="card-title">
                            <a href="{% url 'blog:post-detail' post.slug %}" class="mb-2 lh-sm">{{ post.title }}</a>
                        </h4>
                        <p class="card-text mb-2 lh-base">
                            {{ post.content|truncatechars_html:130|safe }}
                        </p>
                    </div>
                    <div class="mb-0 text-muted d-flex align-items-end align-items-md-center justify-content-between">
                        <div>
                            <a class="d-none d-md-inline category-btn"
                                href="{% url 'blog:category' post.category.slug %}">{{ post.category }}</a>
                            <span>{{ post.last_update|date:"M d" }}</span><span
                                class="dot"></span><span>{{ post.content|readtime }}</span>
                        </div>
                        {% if request.user == post.author %}
                        <div class="action">
                            <a href="{% url 'blog:post-update' post.slug %}" title="Edit post"><i
                                    class="far fa-edit"></i></a>
                            <a href="{% url 'blog:post-delete' post.slug %}" class="ms-1" title="Delete post"><i
                                    class="fas fa-trash"></i></a>
                        </div>
                        {% else %}
                        {% csrf_token %}
                        <button class="bookmark" value="{{ post.pk}}" title="Bookmark story">
                            <i class="far fa-bookmark"></i>
                        </button>
                        {% endif %}
                    </div>
                </div>
                <!-- End author post -->
                <hr class="my-3" />
            </div>
            {% endfor %}
            <br>
            <div class="container my-5 pb-5 d-flex justify-content-center">
                <div class="pagination">
                    {% if page_obj.has_previous %}
                    <a href="?page=1" class="mx-2 ps-1" title="First Page"><i class="fas fa-angle-double-left"></i></a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="mx-2 px-1" title="Previous Page"><i
                            class="fas fa-angle-left"></i></a>
                    {% endif %}

                    {% if author_posts|length > 10 %}
                    <span class="current mx-2">
                        {{ page_obj.number }}
                    </span>
                    {% endif %}

                    {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="mx-2 px-1" title="Next Page"><i
                            class="fas fa-angle-right"></i></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="mx-2 pe-1" title="Last Page"><i
                            class="fas fa-angle-double-right"></i></a>
                    {% endif %}
                </div>
            </div>
            {% else %}
            <div class="col-12 col-lg-7 mx-auto">
                <p>Sorry! {{ user.first_name }} doesn't have any posts published yet.</p>
            </div>
            {% endif %}
        </div>
        <div class="col-md-3">
            <h4>About me</h4>
            <p>{{ user.profile.about }}</p>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'accounts/js/app.js' %}"></script>
{% endblock %}

accounts/templates/accounts/user_saved.html
{% extends "base.html" %}
{% load static %}
{% load post_read_time %}

{% block title %} Saved posts {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid">
    <div class="row">
        <div class="container pt-4">
            <!-- Author posts -->
            {% if bookmarks|length > 0 %}
            {% for bookmark in bookmarks %}
            <div class="col-12 col-lg-6 mx-auto">
                <div class="mycard">
                    <div class="d-flex flex-column">
                        <h4 class="card-title">
                            <a href="{% url 'blog:post-detail' bookmark.post.slug %}"
                                class="mb-2 lh-sm">{{ bookmark.post.title }}</a>
                        </h4>
                    </div>
                    <div class="mb-0 text-muted d-flex align-items-end align-items-md-center justify-content-between">
                        <div>
                            <a class="d-none d-md-inline category-btn"
                                href="{% url 'blog:category' bookmark.post.category.slug %}">{{ bookmark.post.category }}</a>
                            <span>{{ bookmark.post.last_update|date:"M d" }}</span><span
                                class="dot"></span><span>{{ bookmark.post.content|readtime }}</span>
                        </div>
                        {% csrf_token %}
                        <button class="bookmark" value="{{ bookmark.post.pk}}" title="Bookmark story">
                            <i class="fas fa-bookmark"></i>
                        </button>
                    </div>
                </div>
                <!-- End author post -->
                <hr class="my-3" />
            </div>
            {% endfor %}
            {% else %}
            <div class="col-12 col-lg-6 mx-auto">
                <p>You don't have any saved posts. Click the bookmark icon to save posts.</p>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'accounts/js/app.js' %}"></script>
{% endblock %}