accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.signin, name="login"),
    path("logout/", views.signout, name="logout"),
    path("verify/", views.inform_to_verify, name="verify"),
    path("follow/", views.Follow.as_view(), name="follow"),
    path("like/", views.LikePost.as_view(), name="like"),
    path("bookmark/", views.BookmarkPost.as_view(), name="bookmark"),
    path("confirm/<uidb64>/<token>/", views.activate, name="activate"),
    path("<str:uid>/", views.UserProfile.as_view(), name="profile"),
    path("<str:uid>/update/", views.update_profile, name="update-profile"),
    path("<str:uid>/draft/", views.DraftPostList.as_view(), name="draft"),
    path("<str:uid>/saved/", views.SavedPostList.as_view(), name="saved"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("stories/", views.PostList.as_view(), name="post-list"),
    path("search", views.SearchResultsList.as_view(), name="search"),
    path("p/new/", views.PostCreate.as_view(), name="post-create"),
    path("p/<slug:slug>/", views.PostDetail.as_view(), name="post-detail"),
    path("p/<slug:slug>/edit/", views.PostUpdate.as_view(), name="post-update"),
    path("p/<slug:slug>/delete/", views.PostDelete.as_view(), name="post-delete"),
    path("p/<slug:slug>/comments/", views.comments, name="comment-list"),
    path(
        "p/<slug:slug>/comments/<int:pk>/edit/",
        views.CommentUpdate.as_view(),
        name="comment-update",
    ),
    path(
        "p/<slug:slug>/comments/<int:pk>/delete/",
        views.CommentDelete.as_view(),
        name="comment-delete",
    ),
    path("category/<slug:slug>/", views.CategoryView.as_view(), name="category"),
]

django_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("blog.urls")),
    path("ac/", include("accounts.urls")),
    path(
        "accounts/reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from blog.models import Post
from common import utils


class AccountManager(BaseUserManager):
    """A User manager for a custom user model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, first_name, last_name, password, **extra_fields):
        if not email:
            raise ValueError("Users must have an email address.")
        if not first_name:
            raise ValueError("Users must have first name.")
        if not last_name:
            raise ValueError("Users must have last name.")

        email = self.normalize_email(email)
        user = self.model(
            email=email, first_name=first_name, last_name=last_name, **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, last_name, password=None, **extrafields):
        extrafields.setdefault("is_staff", False)
        extrafields.setdefault("is_superuser", False)
        return self._create_user(email, first_name, last_name, password, **extrafields)

    def create_superuser(
        self, email, first_name, last_name, password=None, **extrafields
    ):
        extrafields.setdefault("is_staff", True)
        extrafields.setdefault("is_superuser", True)

        if extrafields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extrafields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True")

        return self._create_user(email, first_name, last_name, password, **extrafields)


class Account(AbstractUser):
    """
    A class implementing a fully featured custom User model with
    admin-compliant permissions.

    first_name, last_name, email and password are required.
    """

    username = None
    email = models.EmailField(
        "email",
        max_length=200,
        unique=True,
    )
    first_name = models.CharField("first name", max_length=150)
    last_name = models.CharField("last name", max_length=150)
    uid = models.CharField("UID", max_length=12)
    is_admin = models.BooleanField(default=False)

    objects = AccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        verbose_name = "account"
        verbose_name_plural = "accounts"

    def __str__(self) -> str:
        return self.email

    def save(self, *args, **kwargs):
        """Assign unique slug before saving the user."""
        if not self.uid:
            self.uid = utils.generate_uid(self.__class__)
        return super().save(*args, **kwargs)


class Profile(models.Model):
    """Profile of the user besides the information provided during sign up."""

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, blank=True)
    about = models.TextField(blank=True)

    def __str__(self):
        return f"{self.user.first_name}'s profile"

    @property
    def following(self):
        """All users followed by this user (following wrt to the user)."""
        return [f.user_following for f in self.user.following.all()]

    @property
    def followers(self):
        """All users following this user (follower wrt the to user)."""
        return [f.user for f in self.user.followers.all()]

    @property
    def likes(self):
        """All posts liked by the user."""
        return [like.post for like in self.user.likes.all()]


class UserFollowing(models.Model):
    """
    Follower and Following relationship between users.

    user: current user
    user_following: target user current user is following
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="following"
    )
    user_following = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="followers"
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "user_following"], name="unique_follow"
            )
        ]


class Bookmark(models.Model):
    """Save posts for later reading."""

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    saved_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "post"], name="unique_bookmarks")
        ]


class Like(models.Model):
    """Like posts that are interesting."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="likes"
    )
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "post"], name="unique_likes")
        ]


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_or_save_profile(sender, instance, created, **kwargs):
    """
    Automatically create a user profile after sign up or
    update it whenever user information is updated.
    """
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

blog/models.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models
from django.urls import reverse

from common import utils


class Category(models.Model):
    """Generic category for posts."""

    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = utils.generate_slug(self.__class__, self.name)
        super().save(*args, **kwargs)


class Post(models.Model):
    """Blog posts written by users or the admin."""

    STATUS = [(0, "Draft"), (1, "Publish")]

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=206, unique=True)
    content = RichTextField()
    status = models.SmallIntegerField(choices=STATUS, default=0)
    last_update = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ["-last_update"]

    def save(self, *args, **kwargs):
        """Assign unique slug from post title."""
        # Only when saving the post for the first time
        if not self.slug:
            self.slug = utils.generate_slug(self.__class__, self.title)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Absolute URL to post detail page."""
        return reverse("blog:post-detail", kwargs={"slug": self.slug})


class Comment(models.Model):
    """User's comment on posts."""

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField(verbose_name="", max_length=300)
    commented_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ["-commented_on"]

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    """A form to accept users's comment on posts."""

    class Meta:
        model = Comment
        fields = ("content",)

blog/templates/blog/category.html
{% extends "base.html" %}
{% block title %} Explore posts in {{ category_posts.0.category.name }} {% endblock %}

{% block main %}

{% include "navbar.html" %}

<div class="container-fluid main">
    <div class="container pt-5">
        <div class="row">
            <div class="col-md-7">
                {% if category_posts|length != 0 %}
                <h3 class="mx-auto mb-5">{{ category_posts.0.category.name }} ({{ category_posts|length }}) </h3>
                {% else %}
                <h4>Currently no posts are published in this category.</h4>
                <a href="{% url 'blog:post-create' %}">Start writing</a>
                {% endif %}
                {% for post in category_posts %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h4 class="card-title mb-0"><a
                                href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a></h4>
                        <div class="small text-muted">
                            <a href="{% url 'accounts:profile' post.author.uid %}"
                                class="author-link">{{ post.author.get_full_name }}</a>
                            <span>&nbsp;|&nbsp;</span>
                            <span>Feb 12</span><span class="dot"></span><span>5 min read</span>
                        </div>
                        <p class="card-text mt-1 text-muted">With supporting text below as a natural lead-in to
                            additional content.
                            With supporting text below as a natural lead-in to additional content...</p>
                        <div class="d-flex justify-content-between">
                            <a href="{% url 'blog:post-detail' post.slug %}" class="read-more">Read more
                                <span>&rarr;</span></a>
                            <button class="bookmark" title="Bookmark story">
                                <i class="far fa-bookmark"></i>
                            </button>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <br>
                <div class="container my-5 pb-5 d-flex justify-content-center">
                    <div class="pagination">
                        {% if page_obj.has_previous %}
                        <a href="?page=1" class="mx-2 ps-1" title="First Page"><i
                                class="fas fa-angle-double-left"></i></a>
                        <a href="?page={{ page_obj.previous_page_number }}" class="mx-2 px-1" title="Previous Page"><i
                                class="fas fa-angle-left"></i></a>
                        {% endif %}

                        {% if category_posts|length > 10 %}
                        <span class="current mx-2">
                            {{ page_obj.number }}
                        </span>
                        {% endif %}

                        {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}" class="mx-2 px-1" title="Next Page"><i
                                class="fas fa-angle-right"></i></a>
                        <a href="?page={{ page_obj.paginator.num_pages }}" class="mx-2 pe-1" title="Last Page"><i
                                class="fas fa-angle-double-right"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-4 d-none d-lg-block">
                <div class="position-sticky" style="top: 2rem">
                    <div class="p-4">
                        <h4>Other</h4>
                        <div class="d-flex flex-wrap popularcategory">
                            {% for category in popular_categories %}
                            {% if category.name != category_posts.0.category.name %}
                            <a href="{% url 'blog:category' category.slug %}"
                                class="btn btn-outline-secondary m-1">{{ category.name }}</a>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/comment.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Comments {% endblock %}

{% block main %}

{% include "navbar.html" %}

<div class="container pt-4 pb-2 px-md-5">
    <a href="{% url 'blog:post-detail' post.slug %}"> <i class="fas fa-chevron-left me-2"></i> Back to post</a>
</div>
<div class="container mb-5 px-md-5">
    <div class="row">
        <div class="col-lg-7 col-md-10 col-sm-12">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show pb-2" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}

            {% if request.user.is_authenticated %}
            <div class="py-4 mb-3 border-bottom">
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <h4>Leave a comment</h4>
                        {{ comment_form|crispy }}
                        <div class="d-flex justify-content-end">
                            <button class="btn btn-primary" type="submit"> Comment </button>
                        </div>
                    </div>
                </form>
            </div>
            {% else %}
            <div class="py-3 mb-2 border-bottom">
                <h4>Comments</h4>
            </div>
            {% endif %}

            {% for comment in comments %}
            <div class="d-flex flex-column comment">
                <div class="d-flex justify-content-between">
                    <div class="small">
                        <a href="{% url 'accounts:profile' comment.author.uid %}" class="text-dark fw-bold">
                            {{ comment.author.get_full_name }}</a>
                        <span class="dot"></span><span class="text-muted">{{ comment.commented_on|date:"M d" }}</span>
                    </div>
                    {% if request.user == comment.author %}
                    <div class="small comment-action">
                        <a href="{% url 'blog:comment-update' comment.post.slug comment.pk %}" title="Edit comment"><i
                                class="far fa-edit"></i></a>
                        <a href="{% url 'blog:comment-delete' comment.post.slug comment.pk %}" class="ms-1"
                            title="Delete comment"><i class="fas fa-trash"></i></a>
                    </div>
                    {% endif %}
                </div>
                <p class="comment-content">{{ comment.content }}</p>
                <!-- <hr class="my-2 col-4"> -->
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/landing_page.html
{% extends "base.html" %}
{% load static %}
{% load post_read_time %}

{% block title %} Welcome to Tomar {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid hero">
    <div class="row flex-lg-row g-5 px-md-5 py-5">
        <div class="col-lg-8 mx-auto">
            <h1 class="display-4 fw-bold lh-1 mb-3">
                Tomar is a platform to read, write and connect with others
            </h1>
            <p class="lead">
                Read stories and turorials, help others by sharing your ideas and
                build a community that grow together.
            </p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <a href="{% url 'accounts:signup' %}" class="btn btn-outline-primary btn-lg px-4 me-md-2">Join now</a>
            </div>
        </div>
    </div>
</div>
<div class="container px-md-5 py-5">
    <h2 class="text-center pb-3">Features</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="col">
            <div class="text-primary pb-2">
                <i class="fas fa-users fa-2x"></i>
            </div>
            <h2>Community</h2>
            <p>
                Support multiple users. Any user with an account can write posts, manage posts, follow and be follwed.
            </p>
        </div>
        <div class="col">
            <div class="text-primary pb-2">
                <i class="fas fa-share-alt fa-2x"></i>
            </div>
            <h2>Share Ideas</h2>
            <p>
                Publish stories about your thoughts, experiences and tutorials which will help others.
            </p>
        </div>
        <div class="col">
            <div class="text-primary pb-2">
                <i class="fas fa-book-open fa-2x"></i>
            </div>
            <h2>Read Stories</h2>
            <p>Read stories written by other users and save your favorite one for later reading.</p>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-7 mx-auto">
            <h2 class="mb-4">Recommended</h2>
            {% for post in featured_posts %}
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="card-title mb-0">
                        <a href="{% url 'blog:post-detail' post.slug %}">{{ post.title|truncatechars:80 }}</a>
                    </h4>
                    <div class="small text-muted">
                        <a href="{% url 'accounts:profile' post.author.uid %}"
                            class="author-link">{{ post.author.get_full_name }}</a>
                        <a class="d-none d-md-inline category" href="{% url 'blog:category' post.category.slug %}">in
                            <strong>{{ post.category }}</strong></a>
                        <span>&nbsp;|&nbsp;</span>
                        <span>{{ post.last_update|date:"M d" }}</span><span
                            class="dot"></span><span>{{ post.content|readtime }}</span>
                    </div>
                    <p class="card-text mt-1 text-muted">{{ post.content|truncatechars_html:130|safe }}</p>
                    <div class="d-flex justify-content-between">
                        <a href="{% url 'blog:post-detail' post.slug %}" class="read-more">Read more
                            <span>&rarr;</span></a>
                        {% csrf_token %}
                        <button class="bookmark" value="{{ post.pk }}" title="Bookmark story">
                            <i class="far fa-bookmark"></i>
                        </button>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col-lg-4 d-none d-lg-block">
            <div class="position-sticky" style="top: 2rem">
                <div class="p-4">
                    <h4>Explore categories</h4>
                    <div class="d-flex flex-wrap popularcategory">
                        {% for category in popular_categories %}
                        <a href="{% url 'blog:category' category.slug %}"
                            class="btn btn-outline-secondary m-1">{{ category.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container px-md-5 my-5 pb-5">
    <div class="d-flex align-items-center justify-content-center">
        <a href="{% url 'blog:post-list' %}" class="btn btn-primary fs-5" id="arrowonhover">All Stories
            <span>&rarr;</span></a>
    </div>
</div>

{% include "footer.html" %}
{% endblock %}

blog/templates/blog/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %} Publish new post {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container-fluid bg-light">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-8 mx-auto">
                <div class="card border-0 shadow rounded-3 mt-3 mb-5">
                    <div class="card-body p-3 p-sm-5" style="box-shadow: 0 0 5px rgba(71, 71, 71, 0.4);">
                        <h5 class="card-title text-center mb-4 fw-light fs-5">Share you ideas to the world</h5>
                        <form method="POST" style="overflow: auto;"> {% csrf_token %}
                            {{ form.media}}
                            {{ form|crispy }}
                            <div>
                                <button class="btn btn-primary mr-2" type="submit" id="submitBtn">Save Draft</button>
                                <a class="btn btn-secondary" href="{% url 'blog:post-list' %}">Cancel </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    // Change active nav element dynamically based on the URL
    $(document).ready(function () {
        const currentUrl = location.pathname;
        $(".navbar-nav li").find("a.active").removeClass("active");
        $(".navbar-nav li").find("a.active").removeAttr("aria-current");
        $('.navbar-nav li a[href="' + currentUrl + '"]').addClass('active');
        $('.navbar-nav li a[href="' + currentUrl + '"]').attr("aria-current", "page");
    });
</script>

<script>
    const status = document.querySelector("#id_status");
    const btn = document.querySelector("#submitBtn");
    status.addEventListener("change", function () {
        if (status.value == 0) {
            btn.innerHTML = "Save Draft";
        } else {
            btn.innerHTML = "Publish";
        }
    })
</script>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load post_read_time %}

{% block title %} {{ post.title }} {% endblock %}

{% block main %}
{% include "navbar.html" %}

<div class="container py-4">
    <div class="row">
        <div class="col-lg-7 mx-auto">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show pb-2" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            {% endif %}
            <article class="blog-post">
                <h1 class="post-title">{{ post.title }}</h1>
                <div class="text-muted d-flex align-items-end justify-content-between">
                    <div class="d-flex">
                        <div>
                            <div class="text-muted">
                                <span>{{ post.last_update|date:"M d" }}</span><span class="dot"></span>
                                <span>{{ post.content|readtime }}</span>
                            </div>
                        </div>
                    </div>
                    {% if request.user == post.author %}
                    <div>
                        <a href="{% url 'blog:post-update' post.slug %}" title="Edit post"><i
                                class="far fa-edit"></i></a>
                        <a href="{% url 'blog:post-delete' post.slug %}" class="ms-1" title="Delete post"><i
                                class="fas fa-trash"></i></a>
                    </div>
                    {% else %}
                    {% csrf_token %}
                    <button class="bookmark" value="{{ post.pk }}" title="Bookmark story">
                        <i class="far fa-bookmark"></i>
                    </button>
                    {% endif %}
                </div>
                <div class="article-post mt-2">
                    {{ post.content|safe }}
                </div>
                <div class="mt-5">
                    <span class="me-2"><strong>Tags: </strong></span>
                    <a href="{% url 'blog:category' post.category.slug %}"
                        class="category-detail">{{ post.category }}</a>
                </div>
                <div class="py-4 my-4 border-top border-bottom">
                    <div class="row">
                        <div class="col-8 d-flex">
                            <div class="me-3 react">
                                {% csrf_token %}
                                <button class="d-flex upvote" value="{{ post.pk }}">
                                    <span class="text-muted"><i
                                            class="far fa-heart text-primary me-2"></i>{{ post.like_set.count }}</span>
                                </button>
                            </div>
                            <a href="{% url 'blog:comment-list' post.slug %}" class="text-muted" title="Commnets"><i
                                    class="far fa-comment-dots me-1"></i>
                                <span>{{ post.comments.count }}</span></a>
                        </div>
                        <div class="col-4 d-flex justify-content-end">
                            <span class="me-2">Share: </span>
                            <a href="#" title="Share to Telegram"><i class="fab fa-telegram me-1"></i></a>
                            <a href="#" title="Share to Facebook"><i class="fab fa-facebook me-1"></i></a>
                            <a href="#" title="Share to LinkedIn"><i class="fab fa-linkedin me-1"></i></a>
                        </div>
                    </div>
                </div>
                <div class="d-flex align-items-start">
                    <div class="about-author d-flex flex-column">
                        <span class="d-block text-muted small">WRITTEN BY</span>
                        <div class="d-flex align-items-end justify-content-md-between mb-1">
                            <a href="{% url 'accounts:profile' post.author.uid %}"
                                class="author-link my-0 me-2">{{ post.author.get_full_name }}</a>
                            {% if request.user != post.author %}
                            {% if request.user in post.author.profile.followers %}
                            <button class="btn btn-sm btn-outline-primary follow"
                                value="{{ post.author.pk }}">Following</button>
                            {% else %}
                            <button class="btn btn-sm btn-primary follow" value="{{ post.author.pk }}">Follow</button>
                            {% endif %}
                            {% endif %}
                        </div>
                        <div>
                            {{ post.author.profile.title }}
                        </div>
                        <div class="text-muted pe-md-5">
                            {{ post.author.profile.about }}
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </div>
    <div class="related mt-5">
        <h3>More from Tomar</h3>
        <hr class="my-4" />
        <!-- Related or popular posts goes here -->
    </div>
</div>

{% include "footer.html" %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'accounts/js/app.js' %}"></script>
<script src="{% static 'accounts/js/app.js' %}"></script>
{% endblock %}