accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.signin, name="login"),
    path("logout/", views.signout, name="logout"),
    path("verify/", views.inform_to_verify, name="verify"),
    path("follow/", views.Follow.as_view(), name="follow"),
    path("like/", views.LikePost.as_view(), name="like"),
    path("bookmark/", views.BookmarkPost.as_view(), name="bookmark"),
    path("confirm/<uidb64>/<token>/", views.activate, name="activate"),
    path("<str:uid>/", views.UserProfile.as_view(), name="profile"),
    path("<str:uid>/update/", views.update_profile, name="update-profile"),
    path("<str:uid>/draft/", views.DraftPostList.as_view(), name="draft"),
    path("<str:uid>/saved/", views.SavedPostList.as_view(), name="saved"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.HomePage.as_view(), name="home"),
    path("stories/", views.PostList.as_view(), name="post-list"),
    path("search", views.SearchResultsList.as_view(), name="search"),
    path("p/new/", views.PostCreate.as_view(), name="post-create"),
    path("p/<slug:slug>/", views.PostDetail.as_view(), name="post-detail"),
    path("p/<slug:slug>/edit/", views.PostUpdate.as_view(), name="post-update"),
    path("p/<slug:slug>/delete/", views.PostDelete.as_view(), name="post-delete"),
    path("p/<slug:slug>/comments/", views.comments, name="comment-list"),
    path(
        "p/<slug:slug>/comments/<int:pk>/edit/",
        views.CommentUpdate.as_view(),
        name="comment-update",
    ),
    path(
        "p/<slug:slug>/comments/<int:pk>/delete/",
        views.CommentDelete.as_view(),
        name="comment-delete",
    ),
    path("category/<slug:slug>/", views.CategoryView.as_view(), name="category"),
]

django_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", include("blog.urls")),
    path("ac/", include("accounts.urls")),
    path(
        "accounts/reset/",
        auth_views.PasswordResetView.as_view(
            template_name="accounts/password_reset_form.html",
        ),
        name="password_reset",
    ),
    path(
        "accounts/password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "accounts/reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("admin/", admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css" />
    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'css/base-style.css' %}">

    {% block page_css %} {% endblock %}
</head>

<body>
    {% block main %} {% endblock %}

    {% block page_js %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>

</html>

templates/footer.html
<footer class="py-4">
    <div class="container px-md-5 py-4 mt-3">
        <div class="d-flex flex-column flex-md-row mb-3 footer-links">
            <a href="#" class="text-muted me-2 me-md-4">Our Team</a>
            <a href="#" class="text-muted me-2 me-md-4">Terms & Privacy</a>
            <a href="#" class="text-muted me-2 me-md-4">Contact</a>
            <a href="#" class="text-muted me-2 me-md-4">About us</a>
        </div>
        <hr class="my-4">
        <div class="d-flex justify-content-between">
            <p>&copy; 2022 Tomar, Inc. All rights reserved.</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3"><a class="link-dark" title="Follow us on LinkedIn" href="#"><i
                            class="fab fa-linkedin"></i></a></li>
                <li class="ms-3"><a class="link-dark" title="Like us on Facebook" href="#"><i
                            class="fab fa-facebook"></i></a></li>
                <li class="ms-3"><a class="link-dark" title="Join us on Telegram" href="#"><i
                            class="fab fa-telegram"></i></a></li>
            </ul>
        </div>
    </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white tomarnav" aria-label="Navigation">
    <div class="container px-md-5">
        <a class="navbar-brand" href="{% url 'blog:home' %}">Tomar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynav"
            aria-controls="mynav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mynav">
            <ul class="navbar-nav mx-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post-list' %}">Stories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post-create' %}">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Author</a>
                </li>
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Sign in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-primary subscribe" id="signup" href="{% url 'accounts:signup' %}">Get
                        Started</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown"
                        aria-expanded="false">More</a>
                    <ul class="dropdown-menu" aria-labelledby="more options">
                        <li><a class="dropdown-item" href="{% url 'accounts:draft' request.user.uid %}"><i
                                    class="far fa-edit me-2"></i>Draft</a></li>
                        <li><a class="dropdown-item" href="{% url 'accounts:saved' request.user.uid %}"><i
                                    class="fas fa-bookmark me-3"></i>Saved</a></li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:profile' request.user.uid %}"><i
                                    class="far fa-user me-3"></i>Profile</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i
                                    class="fas fa-arrow-right me-3"></i>Sign out</a>
                        </li>
                    </ul>
                </li>
                {% endif %}
            </ul>
            <form action="{% url 'blog:search' %}" method="get">
                <input name="q" type="search" class="form-control" placeholder="Search" aria-label="Search">
            </form>
        </div>
    </div>
</nav>